### ISSUE TITLE
Which NACE version is it ?

### ISSUE THREAD

**Issue by Stephane-Perriot** [jnsprnw/nace-codes#4]
There is several NACE version, which one is it ?

Thanks for your work

**Comment by jnsprnw** [comment]
This repository is from an quick prototype some time ago, so I can’t remember the details. I guess it’s the version from the link provided in the description: https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32006R1893

**Comment by Stephane-Perriot** [comment]
Okay, so it's the version 2.  Thank you :)
